name: CI

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      # Self
      - '.github/workflows/ci.yml'
      # Source files
      - '**/*.jsx?'
      - '**/*.tsx?'
      # Stylesheets
      - '**/*.scss'
      # Build configs
      - '.browserlistrc'
      - '.nvmrc'
      - 'tsconfig.json'
      # Linter configs
      - '.eslintignore'
      - '.eslintrc.json'
      - '.prettierrc'
      # Dependencies
      - 'package.json'
      - 'yarn.lock'

jobs:
  frontend_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v2.3.5

      - name: Read .nvmrc
        run: echo NVMRC=`cat .nvmrc` >> $GITHUB_ENV

      - name: Setting up NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NVMRC }}

      - name: Get Yarn cache directory
        run: echo YARN_CACHE_DIR=$(yarn cache dir) >> $GITHUB_ENV

      - name: Use Yarn cache
        uses: actions/cache@v2
        with:
          path: ${{ env.YARN_CACHE_DIR }}
          key: yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: yarn-

      - name: Installing JS packages
        run: yarn install --prefer-offline --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Jest
        run: yarn test:jest

      - name: E2E
        run: yarn test:e2e

      - name: ESLint
        run: yarn lint

      - name: TypeScript
        run: yarn build


